[30] refactorings
dermatz/ddev-woodoo-buildtools-magento pull request #31
Opened 2024-07-23 20:36 UTC by dermatz

2024-07-25 08:44 UTC, t-muir commented on README.md
> +  frontend-update -dev  Update to the latest Main-Branch Version (not recommented)
```suggestion
  frontend-update -dev  Update to the latest Main-Branch Version (not recommended)
```

2024-07-25 08:44 UTC, t-muir commented on README.md
> +  build -f              Builds all configured themes without yes/no question
```suggestion
  build -f              Builds all configured themes without yes/no confirmation
```

2024-07-25 08:44 UTC, t-muir commented on README.md
> +  -f                    Force the build command to run without yes/no question
```suggestion
  -f                    Force the build command to run without yes/no confirmation
```

2024-07-25 08:44 UTC, t-muir commented on README.md
>  This ddev add-on helps you to manage your theme build processes in Magento total easy. You can run a build command to build all your themes or a specific theme. Don't matter if the theme is a Magento
```suggestion
This ddev add-on helps you to manage your theme build processes in Magento easily. You can run a build command to build all your themes or a specific theme. It doesn't matter if the theme is a Magento Standard Theme, a Custom Theme, or a Hyva theme. It automatically takes care of which type of theme you use and builds it for you. If a dependency is missing, Woodoo will install it.
```

2024-07-25 18:50 UTC, Morgy93 requested changes
The recent changes in README.md are not reflected in the help command output and should be updated accordingly.

2024-07-26 07:42 UTC, Morgy93 requested changes

2024-07-26 07:42 UTC, Morgy93 commented on commands/web/woodoo_components/help
>      echo -e "  ${txtcyn}frontend-update -dev${txtrst}  Update to the latest Main-Branch Version (not recommented)"
```suggestion
    echo -e "  ${txtcyn}frontend-update -dev${txtrst}  Update to the latest Main-Branch Version (not recommended)"
```

2024-07-26 07:44 UTC, Morgy93 commented
There's a typo in https://github.com/dermatz/ddev-woodoo-buildtools-magento/blob/main/commands/web/woodoo_components/help#L10 you might want to squash as well:

`dataabase` -> `database`

2024-07-26 08:48 UTC, Morgy93 approved these changes

2024-07-26 08:48 UTC, merged