Update CONTRIBUTING.md with coding standards and best practices
dermatz/ddev-woodoo-buildtools-magento pull request #49
Opened 2024-08-21 06:02 UTC by dermatz

2024-08-22 20:41 UTC, Morgy93 commented on CONTRIBUTING.md
> +![Demo Git commit message helper](https://github.com/d3skdev/git-prefix/raw/master/images/demo.gif)
```suggestion
## VSCode Users

VSCode users automatically apply the workspace settings defined in `.vscode/settings.json`. 

To streamline your workflow, we recommend using the [Git Commit Message Helper](https://marketplace.visualstudio.com/items?itemName=D3skdev.git-commit-message-helper) extension. This tool ensures your commit messages are formatted correctly with the appropriate prefixes, based on the branch name and issue ID from GitHub.

For example: `#123 - Commit Message ...`

![Git Commit Message Helper Demo](https://github.com/d3skdev/git-prefix/raw/master/images/demo.gif)
```

2024-08-22 20:43 UTC, Morgy93 commented on CONTRIBUTING.md
> +-   Avoid global variables, use `local VARIABLE` if possible
```suggestion
-   Avoid global variables, use `local VARIABLE` whenever possible
```

2024-08-23 06:28 UTC, Morgy93 requested changes

2024-08-23 06:28 UTC, Morgy93 commented on CONTRIBUTING.md
>  -   Make sure to have a working local development environment, e.g. ddev
```suggestion
-   Make sure to have a working local development environment of [DDEV](https://github.com/ddev/ddev).
```

2024-10-21 19:02 UTC, dermatz commented
@Morgy93 any news about this PR?

2024-10-21 21:48 UTC, Morgy93 commented
> @Morgy93 any news about this PR?

There's one open conversation that needs to be resolved:
https://github.com/dermatz/ddev-woodoo-buildtools-magento/pull/49#discussion_r1728435592

2024-10-28 07:15 UTC, merged